#这是帮助您开始操作的基本工作流程

名称：CI:CI

#控制工作流程何时运行
在……之上：:
#触发推式或拉式请求事件的工作流，但仅限于“主”分支#触发推式或拉式请求事件的工作流，但仅限于“主”分支
推：:
分支机构：["main"]: [ "主要" ]
pull_request：:
分支机构：["main"]: [ "主要" ]

#允许您从“操作”选项卡手动运行此工作流#允许您从[动作]索引标签手动执行此工作流程
工作流程分派(_D)：:

#工作流运行由一个或多个作业组成，这些作业可以按顺序或并行运行
作业：:
#此工作流包含一个名为“生成”的作业#此工作流包含一个名为“生成”的作业
建立：:
#作业将在其上运行的运行器类型#作业将在其上运行的运行器的类型
run-on:ubuntu-latest: ubuntu-最新

#步骤表示将作为作业的一部分执行的一系列任务#步骤表示将作为作业的一部分执行的一系列任务
步骤：:
#签出$GitHub_WORKSPACE下的存储库，以便您的作业可以访问它#签出$GitHub_WORKSPACE下的存储库，以便您的作业可以访问它
-使用：操作/结帐@v4uses: 操作/结帐@v4

#使用runnershell运行单个命令#使用runnershell运行单个命令
-名称：运行单行脚本name: 运行单行脚本
运行：回显你好，世界！: 回声你好，世界！

#使用runnershell运行一组命令#使用runnershell运行一组命令
-名称：运行多行脚本name: 运行多行脚本
运行：|: |
echo添加要生成的其他操作，
echo测试，并部署项目。
